/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
public class consultaventas extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    Statement  stmt;
    String co,fe,tv,cclie,cvend,st;
      DefaultTableModel  baca =new DefaultTableModel();
    public consultaventas() {
        initComponents();
        setSize(630,500);
        setLocation(340,100);
         baca.addColumn("codigo");
       baca.addColumn("fecha venta");
       baca.addColumn("tipo venta");
       baca.addColumn("codi cliente");
       baca.addColumn("codi venta");
       baca.addColumn("estado");
       venta.setModel(baca);
       conectarJDBC();
    }
 public void conectarJDBC()
    {
    
    String url="jdbc:sqlserver://localhost; databaseName=baca;user=sa; password=123456;";
    try
    {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        con=DriverManager.getConnection(url);
       
    }
    catch(Exception ex)
    {
                JOptionPane.showMessageDialog(rootPane, "Noooooooo", "Conectar", JOptionPane.ERROR_MESSAGE);

    }
    }
 private void mostrar (){ 
         
         String valor=txtda.getText();//segundo paso crear la variable
         
         
         try {
         String sql="select * from venta where fec_venta='"+valor+"'";
         stmt=con.createStatement();
         rs=stmt.executeQuery(sql);//obtenemos la respuesta del sql
         while(rs.next())
         {
             
              String dato[]=new String [6];
                dato[0]=rs.getString(1);
                dato[1]=rs.getString(2);
                dato[2]=rs.getString(3);
                dato[3]=rs.getString(4);
                dato[4]=rs.getString(5);
                dato[5]=rs.getString(6);
                baca.addRow(dato);    
         }
           //con.close();
           //stmt.close();
         }catch(Exception ex){
             JOptionPane.showMessageDialog(rootPane,ex.getMessage());      
         }
         
     }
       private void mostrar2 (){ 
         
         String valor=txtda.getText();//segundo paso crear la variable
         
         
         try {
         String sql="select * from venta where id_clie='"+valor+"'";
         stmt=con.createStatement();
         rs=stmt.executeQuery(sql);//obtenemos la respuesta del sql
         while(rs.next())
         {
             
             String dato[]=new String [6];
                dato[0]=rs.getString(1);
                dato[1]=rs.getString(2);
                dato[2]=rs.getString(3);
                dato[3]=rs.getString(4);
                dato[4]=rs.getString(5);
                dato[5]=rs.getString(6);
                baca.addRow(dato);   
         }
         
           //con.close();
           //stmt.close();
         }catch(Exception ex){
             JOptionPane.showMessageDialog(rootPane,ex.getMessage());      
         }
         
     }
       
               void limpiaTabla(){
        try{
          baca = (DefaultTableModel) venta.getModel();
            int a =baca.getRowCount()-0;
            for(int i=0; i<a; i++)
                baca.removeRow(0); 
        }catch(Exception e){
            System.out.println(e);
        }
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbno = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        venta = new javax.swing.JTable();
        rbape = new javax.swing.JRadioButton();
        txtda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btbus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbno);
        rbno.setText("fecha venta");
        rbno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnoActionPerformed(evt);
            }
        });
        getContentPane().add(rbno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        venta.setBackground(new java.awt.Color(0, 204, 204));
        venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(venta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 120));

        buttonGroup1.add(rbape);
        rbape.setText(" codigo del cliente");
        rbape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbapeActionPerformed(evt);
            }
        });
        getContentPane().add(rbape, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        txtda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaActionPerformed(evt);
            }
        });
        getContentPane().add(txtda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 280, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("consultas venta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        btbus.setText("buscar");
        btbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbusActionPerformed(evt);
            }
        });
        getContentPane().add(btbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel2.setText("total de registro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 60, -1));

        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        jMenu1.setText("buscar ventas ");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("datos venta");

        jMenuItem1.setText("ventas re");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnoActionPerformed
        txtda.setText("");
    }//GEN-LAST:event_rbnoActionPerformed

    private void rbapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbapeActionPerformed
        txtda.setText("");
    }//GEN-LAST:event_rbapeActionPerformed

    private void ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaMouseClicked
        // TODO add your handling code here:
//        btguardar.setEnabled(false);
//        btmodificar.setEnabled(true);
//        bteliminar.setEnabled(true);
//        int fila=vend.getSelectedRow();
//        txtco.setText(vend.getValueAt(fila,0).toString());
//        txtno.setText(vend.getValueAt(fila,1).toString());
//        txtap.setText(vend.getValueAt(fila,2).toString());
//        txtapm.setText(vend.getValueAt(fila,3).toString());
//        txtsu.setText(vend.getValueAt(fila,4).toString());
    }//GEN-LAST:event_ventaMouseClicked

    private void txtdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaActionPerformed

    private void btbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbusActionPerformed
        // TODO add your handling code here:
        int total;
        limpiaTabla();
        if(rbno.isSelected())
        mostrar();
        if(rbape.isSelected())
        mostrar2();
        total=baca.getRowCount();
        txttotal.setText(String.valueOf(total));
        txtda.requestFocus();
        txtda.setText("");
    }//GEN-LAST:event_btbusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new bmenu (). setVisible(true);
        dispose();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      new venta (). setVisible(true);
      dispose();
     
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbape;
    private javax.swing.JRadioButton rbno;
    private javax.swing.JTextField txtda;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTable venta;
    // End of variables declaration//GEN-END:variables
}
