
package ventas;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
public class convendedo1 extends javax.swing.JFrame {
DefaultTableModel baca = new DefaultTableModel();
    Connection con;
    Statement stmt;
    ResultSet rs;
    public convendedo1() {
        initComponents();
         baca.addColumn("codigo");
       baca.addColumn("nombre");
       baca.addColumn("apellido");
       baca.addColumn("apellido materno");
       baca.addColumn("salario");
       
       ;
       this.vend.setModel(baca);
       conectarJDBC() ;
       codi();
        }
       void limpiaTabla(){
        try{
          baca = (DefaultTableModel) vend.getModel();
            int a =baca.getRowCount()-0;
            for(int i=0; i<a; i++)
                baca.removeRow(0); //aquí estaba el error, antes pasaba la i como parametro.... soy un bacín  XD
        }catch(Exception e){
            System.out.println(e);
        }
         }
    private void conectarJDBC() {

        String url = "jdbc:sqlserver://localhost; databaseName=baca;user=sa; password=123456;";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(url);
            JOptionPane.showMessageDialog(rootPane, "TU SI A  BACA ", "Conectar", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Noooooooo", "Conectar", JOptionPane.ERROR_MESSAGE);

        }
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vend = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbodi = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("consulat selecionando la apellido de los clientes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, -1));

        vend.setBackground(new java.awt.Color(51, 255, 153));
        vend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(vend);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 410, 240));

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("direccion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        getContentPane().add(cbodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 80, -1));

        jButton1.setText("cosultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jButton2.setText("salir");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         limpiaTabla();
       String valor=(String)cbodi.getSelectedItem();
        try {
            String pre="select * from vendedor where ape_pat='"+valor+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(pre);//obtener una respuesta
            while(rs.next()){
                String dato[]=new String [5];
                dato[0]=rs.getString(1);
                dato[1]=rs.getString(2);
                dato[2]=rs.getString(3);
                dato[3]=rs.getString(4);
                dato[4]=rs.getString(5);
               
                 
                baca.addRow(dato);
                
//                con.close();
//                stmt.close();
            }
        } 
            catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"nooooo","con sulta no valida por favor",JOptionPane.ERROR_MESSAGE);
        }
        } 
     
         
//         
             private void codi() {
             
        try {
            String pre="select distinct ape_pat from vendedor";
            stmt=con.createStatement();
            rs=stmt.executeQuery(pre);//obtener una respuesta
            while(rs.next()){
                cbodi.addItem(rs.getString(1));
           
                 }
            con.createStatement();
            stmt.executeQuery(pre);
        } 
            catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"nooooo","no es",JOptionPane.ERROR_MESSAGE);

        
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convendedo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convendedo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convendedo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convendedo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convendedo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbodi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable vend;
    // End of variables declaration//GEN-END:variables
}
