/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
public class producto extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement  stmt;
    double p;
    String co,pro,st,sm,smx;
     DefaultTableModel  baca =new DefaultTableModel();
    public producto() {
        initComponents();
        setSize(630,500);
        setLocation(340,100);
         baca.addColumn("codigo");
       baca.addColumn("producto");
       baca.addColumn("stock actual");
       baca.addColumn("stock minimo");
       baca.addColumn("stock maximo");
       baca.addColumn("precio de venta");

        this.var.setModel(baca);
        conectarJDBC();
    }
    public void conectarJDBC()
    {
    
    String url="jdbc:sqlserver://localhost; databaseName=baca;user=sa; password=123456;";
    try
    {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        con=DriverManager.getConnection(url);
        JOptionPane.showMessageDialog(rootPane, "TU SI A BACA ", "Conectar", JOptionPane.INFORMATION_MESSAGE);
    }
    catch(Exception ex)
    {
                JOptionPane.showMessageDialog(rootPane, "Noooooooo", "Conectar", JOptionPane.ERROR_MESSAGE);

    }
    }
     
        private  void llenar()
               
     {
//         cod=Integer.parseInt(txtco.getText()); combertir de string a entero
    co=txtco.getText();
    pro=txtpro.getText();
    st=txtst.getText();
    sm=txtsm.getText();
    smx=txtmx.getText();
    p=Double.parseDouble(txtp.getText());
//    p=Double.parseDouble(txtp.getText());

    }
           private void mostrar(){
     String sql;
        try {
           
             sql="select * from producto";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);//obtener una respuesta
            while(rs.next()){
                String dato[]=new String [6];
                dato[0]=rs.getString(1);
                dato[1]=rs.getString(2);
                dato[2]=rs.getString(3);
                dato[3]=rs.getString(4);
                dato[4]=rs.getString(5);
                 dato[5]=rs.getString(6);
               
                baca.addRow(dato);
                
                        
            }
        } 
            catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"nooooo","con sulta no valida",JOptionPane.ERROR_MESSAGE);
        }
        
    }
             public void limpiar()
               
     {
       
         
      
         
    }
             public void registrar(){
                 int rpt;
                 String sql;
                 rpt=JOptionPane.showConfirmDialog(rootPane,"deseas gravar","gravar",
                         JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
                  
                  
                  
                 try {
                     llenar();
                    sql="insert into producto values( '"+co+"','"+pro+"','"+st+"','"+sm+"','"+smx+"',"+p+")";
                     
                    stmt=con.createStatement();
                     stmt.executeQuery(sql);
                     con.close();
                     stmt.close();
                    
                     
                     
                 } catch (Exception ex) {
                     JOptionPane.showMessageDialog(this,"herrror en cosulta");
                 }
                 
                      
                         
                 
             }
             
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtp = new javax.swing.JTextField();
        txtst = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        var = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btmodificar = new javax.swing.JButton();
        btgrabar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btsali = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("precio venta");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));
        jPanel2.add(txtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 70, -1));
        jPanel2.add(txtst, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 70, -1));

        jLabel3.setText("stock actual");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 70, 20));
        jPanel2.add(txtsm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 70, -1));

        jLabel4.setText("stoc minimo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));
        jPanel2.add(txtmx, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 70, -1));

        jLabel5.setText("stock maximo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));
        jPanel2.add(txtpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 110, 20));

        jLabel2.setText("producto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel2.add(txtco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 80, -1));

        jLabel1.setText("codigo");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 530, 120));

        var.setBackground(new java.awt.Color(102, 255, 153));
        var.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(var);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 700, 120));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmodificar.setText("modificar");
        jPanel1.add(btmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        btgrabar.setText(" grabar");
        btgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgrabarActionPerformed(evt);
            }
        });
        jPanel1.add(btgrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        btneliminar.setBackground(new java.awt.Color(255, 255, 0));
        btneliminar.setText("eliminar");
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        btsali.setBackground(new java.awt.Color(255, 255, 0));
        btsali.setText("salirr");
        btsali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaliActionPerformed(evt);
            }
        });
        jPanel1.add(btsali, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setText("grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        btnuevo.setBackground(new java.awt.Color(204, 204, 0));
        btnuevo.setForeground(new java.awt.Color(204, 0, 0));
        btnuevo.setText("nuevo");
        jPanel1.add(btnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 0));
        jButton2.setText("mostarar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 510, 100));

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText(" registra productos tienda de don pepe");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 360, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgrabarActionPerformed
       registrar();
    }//GEN-LAST:event_btgrabarActionPerformed

    private void btsaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaliActionPerformed
        dispose();
        new bmenu (). setVisible (true);
        
    }//GEN-LAST:event_btsaliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        llenar();
        registrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
mostrar()   ;     // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btgrabar;
    private javax.swing.JButton btmodificar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JButton btsali;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtco;
    private javax.swing.JTextField txtmx;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtpro;
    private javax.swing.JTextField txtsm;
    private javax.swing.JTextField txtst;
    private javax.swing.JTable var;
    // End of variables declaration//GEN-END:variables
}
